

name: simple_server


environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  http: ^0.13.4
  shelf: ^1.2.0
  shelf_router: ^1.1.2
  shelf_static: 1.1.0
  image: ^3.0.2
  mime_type: ^1.0.0
  flutter:
    sdk: flutter
  mysql1: ^0.19.2
  http_status_code: ^0.0.2
